### ISSUE TITLE
ER Modell

### ISSUE THREAD

**Issue by null-git** [polygamma/macio-sigfox-connection#11]
Siehe: 0698bdc432bac75bfa96b840185b071427ccd8ca
Englisch, weil alte Tabelle ist auch auf Englisch benannt. Und auch wenn wir Doku auf Deutsch schreiben, erwartet hoffentlich niemand, dass wir das auch bei der Datenbank oder beim Programmieren machen müssen.

Ich hab für den ersten Punkt statt alles in eine Tabelle zu schmeißen, versucht da was generisches zu bauen, dass beliebig erweiterbar ist, ohne dass man jedes mal tausende alte Tabellen anpassen muss.

Wie wir das mit der Statistik (wie viele Nachrichten kommen an, gehen verloren) machen sollen, weiß ich nicht. Evtl. hat sich das mit unserem Bericht zu Sigfox ja auch erledigt. Ansonsten habe ich einen "measuring_interval" in die "controller" Tabelle aufgenommen, damit sollte das dann zumindest abschätzbar sein.

Den letzten Punkt habe ich nicht ganz verstanden. Ist damit ein Eintrag für jeden Sensor, der die Daten dann einheitlich für den jeweiligen Datentypen umrechnen lässt, gemeint? Könnte das dann nicht auch direkt in die "measurement_options" Tabelle? Da müsste das zwar zu jedem Sensor einzeln angegeben werden, aber ich würde eh davon ausgehen, dass die alle sehr unterschiedliche Ergebnisse raus hauen, die dann erst normalisiert werden müssen.

Die Tabellen "watches" und "watered" könnten auch einfach als Beziehungen dargestellt werden.

Datenbanken und so ist bei mir ewig her, ich hoffe, ich habe nicht zu sehr gegen Best Practices, Standards oder die Anforderungen verstoßen.

**Comment by null-git** [comment]
"watches" ist halt nur durch die beiden id's eindeutig (entweder Eintrag ist da, oder nicht), "watered" nicht (neuer Eintrag in Tabelle für jede Bewässerung, dort könnte man auch "timestamp" als zusätzlichen PK nehmen, aber komplexere Datentypen als Keys sind gruselig).

"plant" hat ein Feld fürs Kommentar. Ich dachte, die Fotos liegen dann irgendwo im FS mit nem Pfad wie "/bilder/<planze.id>", dann muss da kein zusätzlicher Eintrag rein.

Was ich noch gerne ändern würde:
"watches" kann man gut mit der "supervise/responsible" relation vereinigen als Tabelle "role" wo dann "watcher/supervisor" drin steht. Wäre dann halt wieder generischer und lässt auch andere Rollen zu (z.B. Urlaubsvertretung, ..)

**Comment by Belethil** [comment]
Gefällt mir auch schon recht gut, habe auch noch ein paar Anmerkungen:
- bei Pflanze - Spezies ist die Relation falschrum beschriftet
- Den PK bei watered finde ich so auch nicht notwendig, da deine Abfrage nach drei Kriterien noch ausreichend übersichtlich ist und eine "Bewässerungs-ID" nicht so richtig aussagekräftig ist, aber das kann man so und so machen, ist also nicht so wichtig 
- is_active bei einer Pflanze könnte man auch is_alive nennen, damit klar ist was man damit aussagen will
- Wie die measurement options in die Sache reinspielen wirkt auf mich noch etwas clunky, auch wenn ich spontan keine bessere Lösung sehe. Ich bin mir zudem nicht sicher (auch wenn das in den Anforderungen nicht so steht) ob es nicht sinnvoller ist, diese Angaben pro Pflanzentyp zu speichern
- Die Fotos sollte man, zumindest als Pfad, auch in der DB speichern; einfach davon auszugehen dass da jemand sein FS schon sinnvoll pflegt ist glaube ich keine so gute Idee :D

**Comment by null-git** [comment]
> * Den PK bei watered finde ich so auch nicht notwendig, da deine Abfrage nach drei Kriterien noch ausreichend übersichtlich ist und eine "Bewässerungs-ID" nicht so richtig aussagekräftig ist, aber das kann man so und so machen, ist also nicht so wichtig

Naja. Wir brauchen noch einen zusätzlichen Key, um den CK eindeutig zu machen. Die gieß-History sollte ja schon gespeichert werden, damit der Zeitpunkt des nächsten Gießens geschätzt werden kann (ist eine Anforderung). Und nur die IDs wären halt jedes mal die selben. Dann hätten wir keine eindeutigen Keys mehr und würden jedes mal die Einträge überschreiben.

> * Die Fotos sollte man, zumindest als Pfad, auch in der DB speichern; einfach davon auszugehen dass da jemand sein FS schon sinnvoll pflegt ist glaube ich keine so gute Idee :D

Ich würde auch nicht davon ausgehen, dass das jemand händisch gut Pflegt :D 
Allerdings wird das Bild ja per Webinterface hochgeladen und dann programmatisch abgelegt und sollte so auch programmatisch gefunden werden können. Aber an sich ist mir das auch ein bisschen egal und wir können klar den Pfad da noch mit rein nehmen.

Bei den anderen Punkten stimme ich dir zu.

**Comment by null-git** [comment]
Fix für die Fehler und img_path: 0698bdc432bac75bfa96b840185b071427ccd8ca

Generische Rollen: 671c1daa124a4e188e217478ef4639396dfc14f4

**Comment by null-git** [comment]
Das Importscript ist jetzt auf dem selben Stand, wie das ER Modell. Abhängigkeiten stehen in der README.md und es kann einfach ohne Argumente ausgeführt werden. Es dumpt dann alle Tables, erzeugt sie neu und gibt sie dann aus.

Von den measurements werden nur die ersten 50 importiert. Um das auszuschalten kann einfach die "all_measurements" Variable auf True gesetzt werden. Dauert dann halt ein bisschen.

Wenn ihr in der Datenbank selbst unterwegs seit: alle Tabellen bekommen von dem Skript den "wip_" Präfix (ist auch per Variable änderbar), so dass auch an verschiedenen Versionen der Migration parallel gearbeitet werden kann.

Ansonsten sind die created_at und changed_at Attribute noch ein bisschen random verteilt, das sollte noch vereinheitlicht werden. Gerade will ich nicht mehr auf den Monitor schauen, sondern ins Wochenende :D Wenn sich das jemand anders vornehmen will: viel Spaß!

**Comment by Belethil** [comment]
Gefällt mir gut, das skript ist sauber und übersichtlich und gut durchdacht; werde es auch nochmal testen und dann nochmal feedback geben :)

**Comment by polygamma** [comment]
Habe am Skript soweit auch nichts auszusetzen, teilweise syntaktisch ein bisschen unterschiedlich, mal Strings appenden mit `+`, mal wird der `%` Formatter genutzt, oder auch `{}` mit `.format()`, aber das ändert ja nichts relevantes an der Funktionalität

**Comment by null-git** [comment]
Ja, das ist vor allem bei den Funktionen, die ich mir aus dem Internet kopiert habe. {} ist eigentlich schöner, sollte ich mich mal dran gewöhnen, aber den PEP gibt es ja auch erst seit drei Jahren..

 Ich räume das heute Abend noch mal ein bisschen auf. Würde dann auch alle "timestamp" Spalten in "created_at" umbenennen, damit das ein bisschen einheitlicher ist.

**Comment by jakunar** [comment]
Abgesehn davon, dass ich nicht unbedingt ein regelmäßiger Python oder SQL Nutzer bin, schaut das doch sehr gut aus und seit deinen letzten Änderungen ist mir auch keine inkonsistenter Stil mehr aufgefallen.
Kriegt nen go von mir.

**Comment by vajaco** [comment]
Jo, sieht gut aus. Müsste nur noch in den master gemergt werden.

**Comment by null-git** [comment]
Aktuelle Version ist im privaten Repo gemerged
