### ISSUE TITLE
Datenbankverbindung abschließen

### ISSUE THREAD

**Issue by Belethil** [polygamma/macio-sigfox-connection#13]
Um die Datenbankverbindung fertigzustellen, also auch die Function-Apps anzubinden, müssen noch ein paar Dinge erledigt werden:

- [ ] Im ER-Modell wird die Device-ID (also die des Herstellers) nicht erfasst; nur diese lässt sich aber z.B. vom Sigfox-Controller senden - dazu wird also noch eine Spalte benötigt
- [ ] Das Migrationsskript muss anschließend noch aktualisiert werden
- [ ] Die eigentliche Migration der Datenbank muss durchgeführt werden

Zeitkritisch, weil wir die Function-App auf die Datenbank angepasst schreiben müssen (und auch die Sigfox-Callbacks damit zusammenhängen)

**Comment by Belethil** [comment]
Punkt 1 bedeutet btw, dass auch die functions immer erst mal die Datenbank-ID des jeweiligen controllers abfragen müssten. Das ist natürlich mehr traffic, was nicht immer wünschenswert ist - dafür wird die Datenbank vereinheitlicht... die Alternative wäre wie gesagt, dass man eben direkt die Device-ID auch in der Datenbank als PK nutzt (die sollten einzigartig genug sein), aber dann hat man eben ein sehr lustiges Chaos zwischen ESP-IDs und Sigfox-IDs und was da noch so dazukommt vielleicht, und irgendwer müsste diese IDs ja bei der Registrierung eines neuen Geräts manuell eintragen, im Gegensatz zu nem automatisch inkrementierten surrogate... bin mit beidem nicht glücklich :D Jan fragen?

**Comment by polygamma** [comment]
Ich denke, man sollte die ID, so wie wir sie aktuell in der DB stehen haben (und dort auch generieren lassen), auf dem Controller im Sourcecode eintragen und diese dann mitsenden. Anderenfalls lachen wir uns *eventuell* Probleme in der Zukunft an, z. B. identische ID's zwischen Geräten weil unterschiedliche Hersteller aber selbes ID-Muster, oder, dass so eine ID überhaupt nicht vorhanden ist, oder sie nicht auslesbar ist, oder oder oder... Man hat zwar minimalen Overhead, weil man in dem Fall noch eine weitere ID mitsenden müsste, aber da kann man ja einfach nen integer nehmen und das sind dann 2 byte, sollten wir überleben. Sourcecode muss dann natürlich auch angepasst werden pro Gerät, aber das ist nun auch kein Beinbruch.

**Comment by null-git** [comment]
Ich stimme dir da zu @polygamma. Sollten wir aber noch mal mit macio besprechen. Ist ja schon blöd, dass man dann erst einen Controller in die DB einträgt, die ID bekommt und dann noch mal flashen muss.

Ich mach den Rest mal kurz fertig und mache dann auch eine Migration mit den ganzen neuen Daten. Kleine Vorwarnung: Die Zeit Tabellen heißen gleich wieder "timestamp" statt "created_at" und gibt es auch nur noch in den Tabellen, bei denen das in der DB vermerkt ist.

**Comment by null-git** [comment]
So, die aktuellste Version ist gepushed und ich habe alle Daten noch mal migriert. Präfix für alle Tabellen ist immer noch "wip_".

Es ist zwar schön, wenn die Function Apps für beide DB fertig sind, aber an sich ist es ja auch ein bisschen quatsch, die parallel zu befüllen (außer vielleicht für Testzwecke), wenn wir vor Ende eh noch mal eine Migration machen.
