### ISSUE TITLE
3D-Modell für Controller

### ISSUE THREAD

**Issue by polygamma** [polygamma/macio-sigfox-connection#14]
Siehe: https://github.com/polygamma/macio-sigfox-connection/blob/3d-modell/rahmen/rahmen.stl

Erster Vorschlag von meiner Seite, bitte Feedback.
Controller reinpacken, mit der "Lasche" an den Topf hängen -> profit.

Erstellt habe ich es hiermit: https://www.freecadweb.org/

**Comment by Belethil** [comment]
Hmm, wenn ich das richtig verstehe hängt das Gehäuse dann allerdings mit einer offenen Seite am Topf, aye? :D Da müsste man nun natürlich hoffen, dass beim Gießen kein Wasser über den Rand läuft... 

Jan hätte gerne eine Variante mit irgendeiner Art von "Deckel", damit das zumindest etwas vor Spritzwasser geschützt ist :D aber die Idee der Aufhängung finde ich gut so

**Comment by polygamma** [comment]
Die Leute dürften gerne imstande sein, eine Blume zu gießen, ohne dabei das Zimmer unter Wasser zu setzen ;D Aber ist ein valider Punkt, ich bastel nochmal eine Art "Deckel" dazu

**Comment by polygamma** [comment]
Siehe https://github.com/polygamma/macio-sigfox-connection/blob/3d-modell/rahmen/rahmen.stl und https://github.com/polygamma/macio-sigfox-connection/blob/3d-modell/rahmen/deckel.stl

**Comment by jakunar** [comment]
Schaut an sich ganz gut aus, insbesondere den Deckel zu reinschieben find ich cool.
Bei der Lasche hängt es etwas vom Top der Pflanze ab, ob das funktioniert.
Etwas generisches mit flexiblerer Einsatzmöglichkeit ist mir aber bisher auch nicht wirklich eingefallen.

**Comment by jakunar** [comment]
Ein eventuelles Problem könnte der DHT22 sein. Wenn ich mich richtig an Jans Ausführung erinnere, soll der die Umgebungswerte (Temperatur und Luftfeuchtigkeit) messen und dafür müsste er sich idealerweise, zumindest mit dem Sensorteil, außerhalb des Gehäuses befinden.

**Comment by polygamma** [comment]
Die Sensoren sollen ja auch nicht in das Gehäuse, nur der Controller. Da passt der MKRFOX1200 genau rein, nach "oben" gehen dann die Kabel durch den Deckel nach draußen, da sollten dann die Sensoren hängen

**Comment by jakunar** [comment]
Und dafür müssten wir, also vermutlich ich, eine Lösung für dessen Position in Relation zum Arduino haben. Haben ich kann mich nicht entscheiden, weil der Sensor auf die Pins blöde auf dem Break-out-Board positioniert sind, im Grunde muss das ganze SensorBoard draußen hängen und bruach dann aber ne Überdachung und nen Kabel Eingang.. hat jemand nen Vorschlag?

**Comment by polygamma** [comment]
Was man sich auch noch überlegen muss: Wie die Controller ihren Strom bekommen, aber da ich das nicht weiß, was macio da vorhat, habe ich das noch nicht mit eingeplant.

**Comment by jakunar** [comment]
Wenn ich das richtig verstanden habe, soll da ne Batterie rein. also keine externe Stromquelle.
@Belethil hatten wir Jan gesagt, welche Batterie wir brauchen?

@polygamma Deckel und somit Kabelausgang oben erhöht die Gefahr, dass Spritzwasser reinläuft.
Halte den "Deckel" unten für sinnvoller, wenngleich auch etwas aufwendige in der Gestaltung

**Comment by polygamma** [comment]
@jakunar - sind sie bereit, so lange Kabel zu verwenden?

**Comment by polygamma** [comment]
Wenn wir wissen, was für Batterien verwendet werden, würde ich das nochmal einarbeiten, sonst würde ich gerne erstmal auf das Feedback von macio warten

**Comment by null-git** [comment]
Danke für den Entwurf! Für einen ersten Prototypen halte ich den auf jeden Fall für sehr vorzeigbar.

Das Ding, was wir dann nach Hamburg schicken, soll ja schon den Kasten bekommen. Und ich bin mir ziemlich sicher, dass Jan sagte, dass der dann erst mal mit externer Stromquelle angetrieben werden soll. Ich weiß auch gar nicht, ob wir da letztes mal schon was konkretes zu der entgültigen Stromquelle gesagt haben, also was für eine Batterie das werden soll oder so.

**Comment by vajaco** [comment]
Das sieht schonmal gut aus. Wir hatten in der Doku ein paar mögliche Stromquellen aufgelistet und beim vorletzten Treffen wurde gesagt, dass macio Batterien besorgen würde.

**Comment by jakunar** [comment]
So, ich hab das Case zuhause und mal ein wenig rum probiert, gemessen und nachgedacht.
Fakt ist auf jeden Fall schon mal, dass man den Deckel nicht hinein bekommt.

Das Gehäuse steht mit dem Schlitz für den Deckel zu mir:
1. Deckel gemessen:
  - H:  1,50 mm
  - L: 29,00 mm
  - B: 80,00 mm
2. Rahmen gemessen:
  - Henkel B: 10,00 mm
  - H: 42,00 mm
  - L: 70,65 mm
  - Wandstärke gegenüber des Schlitzes: 4,30 mm
  - B außen: 33 mm
  - B innen: 24,80 mm
  - Wandstärke: 4,10 mm
  - Breite des Schlitzes: 28,20 mm - 28,40 mm

(In den Schlitz komm ich mit meinem Messschieber leider nicht richtig rein.)

Wenn man nur einen Steg vom Deckel reinschiebt stell man fest, dass man zwar in die Führung im Rahmen reinkommt, man muss aber etwas Kraft anwenden. Sitzt also gut, bis sehr eng.
Da das als Problem vermutet wurde, wurde der Deckel noch einmal mit 1,20 mm Stärke gedruckt.
Das geht entspannt hinein, ist mir persönlich aber etwas zu lose.

Ich vermute, dass die kleineren Ungenauigkeiten von der begrenzten Präzision des 3D-Druckers verursacht werden.
Die größeren, also dass der Deckel nicht passt oder dass die Gesamtlänge nicht stimmt, könnten daher kommen, dass man für Überhänge, also nur seitlich fixierte Teile, abstützen muss. Vielleicht waren diese Stützen nicht exakt in dem Ausmaß das sie sein sollten.

**Comment by jakunar** [comment]
Mal noch ne andere Frage an den Designer: Hattest du die offene Seite oder die geschlossene Seite als ersten Einschub im Kopf?

**Comment by polygamma** [comment]
Die Frage verstehe ich nicht

**Comment by polygamma** [comment]
Den Rest vom Text kann ich so auch nicht nachvollziehen, was genau du meinst, gucken wir uns morgen bei macio an

**Comment by polygamma** [comment]
Gerade nochmal in FreeCAD nachgemessen, Schlitz sollte genau 29mm breit werden, wenn er echt bei knapp über 28mm liegt, ist der Drucker nicht gut.

![capture](https://user-images.githubusercontent.com/20651500/49599525-8870ee80-f981-11e8-90a9-12512b19f882.PNG)

**Comment by polygamma** [comment]
Die neuen Modelle sind jetzt darauf ausgelegt, dass das Controller samt Breadboard dort reinpasst. Sollte automatisch genug Platz für Batterie, Kabel etc. schaffen.

Siehe [Rahmen 2](https://github.com/polygamma/macio-sigfox-connection/blob/3d-modell/rahmen/rahmen2.stl) und [Deckel 2](https://github.com/polygamma/macio-sigfox-connection/blob/3d-modell/rahmen/deckel2.stl)

**Comment by polygamma** [comment]
Passt.
