### ISSUE TITLE
Vergleich verschiederer IOT / LPWAN Netzwerke

### ISSUE THREAD

**Issue by null-git** [polygamma/macio-sigfox-connection#6]
Gewünschte Punkte:
 * Mobilität
 * Netzabdeckung
 * Skalierbarkeit
 * Wartbarkeit
 * Konfiguration
 * Kommunikation
 * Kosten
 * ...

Netzwerke:
 * [Sigfox](https://en.wikipedia.org/wiki/Sigfox)
 * [LoRa](https://en.wikipedia.org/wiki/LoRa)
 * ~~[NB-Fi](https://en.wikipedia.org/wiki/NB-Fi)~~
 * [NB-IoT](https://en.wikipedia.org/wiki/Narrowband_IoT)
 * [Wi-Fi HaLow](https://en.wikipedia.org/wiki/IEEE_802.11ah) (evtl ?)
   - einziger (?) offener Standard
   - leider noch keine Hardware verfügbar
   - evtl als Zukunftsausblick mit der Möglichkeit, dass der in Consumer Grade WLAN Routern verbaut werden könnte

**Comment by polygamma** [comment]
Mögliche DEV-Kits:
- LoRa - http://www.dragino.com/products/lora/item/120-lora-iot-kit.html
- NB-Fi - http://www.swisstraffic.ch/en/content/iot/technicaldescriptions/w7e071b0b3b2c002f3aa54f3136e3a6e

**Comment by polygamma** [comment]
Vergleich NB-IoT (nicht NB-Fi) vs. LoRa vs. Sigfox - https://www.link-labs.com/blog/nb-iot-vs-lora-vs-sigfox

**Comment by null-git** [comment]
Ich würde doch eher  CAT-NB1 (NB-IoT) statt NB-Fi als dritten Punkt nehmen. NB-Fi hat ähnlich technologischen Stärken und Schwächen wie Sigfox / LoRa / andere LPWAN und hat eine wesentlich geringere Verbreitung. NB-IoT Rollout ist zwar noch nicht in Kiel angekommen, wird aber durch die Telekom und Vodafone gerade in Deutschland deployed und ist halt Technologie in einem lizenzierten Frequenzspektrum welche viel Infrastruktur von bestehenden Mobilfunknetzen nutzen kann.
Auch wenn wir in Kiel damit noch nicht arbeiten können, ist das für Macio perspektivisch vermutlich interessanter.

Weltweite Deployment Map:
https://www.gsma.com/iot/deployment-map/

**Comment by vajaco** [comment]
Habe den Technologievergleich, wie besprochen, einmal korrekturgelesen und zu den zwei TODOs etwas rausgesucht.

**Comment by polygamma** [comment]
Das, was aktuell im Branch zu finden ist, gefällt mir. Sollen die möglichen Development Kits eventuell noch mit im Text aufgenommen werden?

**Comment by Belethil** [comment]
Sehr ordentlich, gefällt mir gut. Würde mich dem Vorschlag anschließen, die verfügbaren DevKits kurz anzureißen, da das für macio sicher interessant ist und sie dann entscheiden können, ob sie uns eines davon besorgen

**Comment by vajaco** [comment]
Dann wäre es vielleicht auch sinnvoll den Stromverbrauch / die Stromversorgung der Devkits mit in den Vergleich aufzunehmen.

**Comment by null-git** [comment]
Ich hab das von @polygamma vorgeschlagene Devkit mit rein genommen bei einem Anbieter, der das aus Deutschland losschicken würde (www.exp-tech.de) und von dem selben Shop auch noch ein NB-IoT Shield. Wirklich zusätzliche Hardware (maximal noch Arduinos) würden da ja nicht wirklich benötigt.

Stromverbrauch könnten wir noch mit rein nehmen, aber die vorgeschlagenen Geräte sollen ja nur Beispiele sein. Wenn wir uns für eine konkrete andere Technologie entscheiden, können wir da ja noch mal genau nach Anforderungen schauen.
