### ISSUE TITLE
Stromverbrauch bestimmen

### ISSUE THREAD

**Issue by Belethil** [polygamma/macio-sigfox-connection#7]
Der Stromverbrauch des MKRFOX1200 soll bestimmt und analysiert werden. Außerdem sollen wir Möglichkeiten zur Optimierung des Stromverbrauchs dokumentieren.

Dieser Post https://forum.arduino.cc/index.php?topic=499101.0 impliziert, dass es in der Standardkonfiguration Probleme mit dem Stromverbrauch gibt; Lösungsvorschläge werden dort ebenfalls dargestellt. Das müsste sich jemand mal genauer ansehen.

**Comment by vajaco** [comment]
Im Datenblatt https://cdn.sparkfun.com/datasheets/Dev/Arduino/Boards/Atmel-42181-SAM-D21_Datasheet.pdf#G60.2354729 ist unter 36.6 eine Tabelle zur Power Consumption.

**Comment by Belethil** [comment]
Jonni konnte da auch nichts weiteres zu finden, insofern würde ich sagen, wir schreiben diese Abschätzung der Werte mit den gefundenen Quellen rein.

**Comment by vajaco** [comment]
Habe jetzt ein Kapitel zur Stormversorgung/Stromverbrauch auf einem eigenen Branch hinzugefügt.

**Comment by polygamma** [comment]
Habe dem nichts weiter hinzuzufügen

**Comment by jakunar** [comment]
Ich habe für kommende Stromverbrauchsbestimmungen ein Kabel vorbereitet, sodass man sich zukünftig lediglich bei einem Multimeter treffen müsste.

**Comment by jakunar** [comment]
@vajaco Magst du die Doku für die Messwerte noch anpassen oder mir diese nochmal zukommen lassen, dann würde ich mich morgen früh nochmal daran setzen, Falls Du die Doku machst, les ich morgen früh Korrektur.

**Comment by vajaco** [comment]
Ich war gerade dabei. Habe die Messwerte jetzt in die Doku eingefügt. https://github.com/polygamma/macio-sigfox-connection/commit/4d31f1ee680600a86ee6a51d4c697892e25364f6.
