### ISSUE TITLE
Erweiterung der Einführung der Dokumentation 

### ISSUE THREAD

**Issue by Belethil** [polygamma/macio-sigfox-connection#8]
In der Dokumentation sollen die Anweisung zur Einrichtung der Chips, insbesondere auch auf der Hardware-Seite und die Anweisungen aus der Arduino-Dokumentation, genauer erklärt werden.

**Comment by Belethil** [comment]
habe mal was dazu geschrieben, bitte einmal gegenlesen und bescheid geben, falls da noch was fehlt/nicht stimmt (war mir nicht sicher ob ich bei der Verkabelung was vergessen habe, habe ja gerade kein board hier).

**Comment by null-git** [comment]
Siehe Kommentare:
https://github.com/polygamma/macio-sigfox-connection/commit/dbb40132e36a2f9702830ca19a441c4ff752a303

**Comment by polygamma** [comment]
Habe den Kommentaren von @null-git nichts hinzuzufügen

**Comment by Belethil** [comment]
Änderungswünsche implementiert, würde das dann als abgeschlossen betrachten.

**Comment by jakunar** [comment]
Jup, seh auch nichts mehr.
